"""

Export router — multi-format session and brief export.

Supports markdown (for Notion/Docs), plain text (for iMessage/WhatsApp), and JSON.

"""

from uuid import UUID

from datetime import datetime



from fastapi import APIRouter, Depends, HTTPException, Query

from fastapi.responses import PlainTextResponse, JSONResponse

from sqlalchemy import select

from sqlalchemy.ext.asyncio import AsyncSession

from sqlalchemy.orm import selectinload



from db.postgres import get_db

from models.tables import DailySession, DailyBrief, Observation

from schemas.session import SessionOut, ObservationOut, DailyBriefOut



router = APIRouter(prefix="/sessions", tags=["export"])





def _format_time(dt: datetime) -> str:

    """Format datetime to readable time string."""

    return dt.strftime("%-I:%M %p") if dt else ""





def _tags_str(tags: list[str]) -> str:

    """Format tags as backtick-wrapped inline labels."""

    return " ".join(f"`#{t}`" for t in tags) if tags else ""





def _session_to_markdown(session: DailySession) -> str:

    """Export a full session as formatted Markdown."""

    date_str = session.session_date.strftime("%B %d, %Y")

    name = session.name or date_str

    lines = [f"# {name}", ""]



    if session.observations:

        lines.append("## Observations")

        lines.append("")

        for i, obs in enumerate(session.observations, 1):

            time_str = _format_time(obs.created_at) if obs.created_at else ""

            tags = _tags_str(obs.sector_tags if isinstance(obs.sector_tags, list) else (

                [obs.sector_tags] if obs.sector_tags else []

            ))

            header = f"### {i}. {obs.title}"

            if time_str:

                header += f" ({time_str})"

            if tags:

                header += f" {tags}"

            lines.append(header)

            if obs.body:

                lines.append(obs.body)

            if obs.voice_transcript and obs.voice_transcript != "[transcription failed]":

                lines.append(f"\n> *Voice:* {obs.voice_transcript}")

            if obs.image_summary and obs.image_summary != "[image analysis failed]":

                lines.append(f"\n> *Image:* {obs.image_summary}")

            lines.append("")



    # Include latest brief if present

    if session.briefs:

        brief = session.briefs[-1]

        lines.append("---")

        lines.append("")

        lines.extend(_brief_to_markdown_lines(brief))



    lines.append("")

    lines.append("---")

    lines.append("*Generated by Coviction*")

    return "\n".join(lines)





def _brief_to_markdown_lines(brief: DailyBrief) -> list[str]:

    """Convert a brief to markdown lines (reusable for full session and brief-only export)."""

    lines = ["## Daily Brief", ""]

    if brief.summary:

        lines.append(f"**Summary:** {brief.summary}")

        lines.append("")

    if brief.tags:

        lines.append(f"**Themes:** {', '.join(brief.tags)}")

        lines.append("")

    if brief.signals:

        lines.append("**Signals:**")

        for s in brief.signals:

            lines.append(f"- {s}")

        lines.append("")

    if brief.actions:

        lines.append("**Follow-ups:**")

        for a in brief.actions:

            lines.append(f"- [ ] {a}")

        lines.append("")

    return lines





def _session_to_plaintext(session: DailySession) -> str:

    """Export session as plain text for sharing via message/email."""

    date_str = session.session_date.strftime("%B %d, %Y")

    name = session.name or date_str

    obs_count = len(session.observations) if session.observations else 0

    lines = [f"{name} ({obs_count} observations)", ""]



    if session.observations:

        for i, obs in enumerate(session.observations, 1):

            tags = ", ".join(obs.sector_tags) if isinstance(obs.sector_tags, list) and obs.sector_tags else ""

            line = f"{i}. {obs.title}"

            if tags:

                line += f" [{tags}]"

            lines.append(line)

            if obs.body:

                # Truncate long bodies for sharing

                body_preview = obs.body[:200] + "..." if len(obs.body) > 200 else obs.body

                lines.append(f"   {body_preview}")

        lines.append("")



    if session.briefs:

        brief = session.briefs[-1]

        lines.append("---")

        lines.append("")

        if brief.summary:

            lines.append(f"Summary: {brief.summary}")

            lines.append("")

        if brief.signals:

            lines.append("Top signals:")

            for s in brief.signals:

                lines.append(f"  * {s}")

            lines.append("")

        if brief.actions:

            lines.append("Follow-ups:")

            for a in brief.actions:

                lines.append(f"  [] {a}")

            lines.append("")



    lines.append("-- Generated by Coviction")

    return "\n".join(lines)





def _brief_to_plaintext(brief: DailyBrief) -> str:

    """Export brief only as plain text."""

    lines = ["Daily Brief", ""]

    if brief.summary:

        lines.append(brief.summary)

        lines.append("")

    if brief.signals:

        lines.append("Signals:")

        for s in brief.signals:

            lines.append(f"  * {s}")

        lines.append("")

    if brief.actions:

        lines.append("Follow-ups:")

        for a in brief.actions:

            lines.append(f"  [] {a}")

        lines.append("")

    lines.append("-- Generated by Coviction")

    return "\n".join(lines)





# ── Session Export ────────────────────────────────────────



@router.get("/{session_id}/export")

async def export_session(

    session_id: UUID,

    format: str = Query("markdown", regex="^(markdown|text|json)$"),

    db: AsyncSession = Depends(get_db),

):

    """Export a full session in the requested format.



    Formats:

    - markdown: Structured Markdown with headers, tags, checkboxes (for Notion/Docs)

    - text: Plain text for iMessage, WhatsApp, email

    - json: Full JSON dump for data portability

    """

    result = await db.execute(

        select(DailySession)

        .options(selectinload(DailySession.observations), selectinload(DailySession.briefs))

        .where(DailySession.id == session_id)

    )

    session = result.scalar_one_or_none()

    if not session:

        raise HTTPException(status_code=404, detail="Session not found")



    if format == "markdown":

        content = _session_to_markdown(session)

        return PlainTextResponse(content, media_type="text/markdown")

    elif format == "text":

        content = _session_to_plaintext(session)

        return PlainTextResponse(content, media_type="text/plain")

    else:  # json

        obs_list = [ObservationOut.model_validate(o).model_dump(mode="json") for o in (session.observations or [])]

        brief = None

        if session.briefs:

            brief = DailyBriefOut.model_validate(session.briefs[-1]).model_dump(mode="json")

        return {

            "id": str(session.id),

            "session_date": session.session_date.isoformat(),

            "name": session.name,

            "observations": obs_list,

            "brief": brief,

            "exported_at": datetime.utcnow().isoformat(),

        }





# ── Brief-Only Export ─────────────────────────────────────



@router.get("/{session_id}/brief/export")

async def export_brief(

    session_id: UUID,

    format: str = Query("markdown", regex="^(markdown|text)$"),

    db: AsyncSession = Depends(get_db),

):

    """Export just the daily brief in markdown or plain text."""

    result = await db.execute(

        select(DailyBrief)

        .where(DailyBrief.session_id == session_id)

        .order_by(DailyBrief.created_at.desc())

        .limit(1)

    )

    brief = result.scalar_one_or_none()

    if not brief:

        raise HTTPException(status_code=404, detail="No brief generated yet")



    if format == "markdown":

        lines = _brief_to_markdown_lines(brief)

        lines.append("")

        lines.append("---")

        lines.append("*Generated by Coviction*")

        return PlainTextResponse("\n".join(lines), media_type="text/markdown")

    else:

        content = _brief_to_plaintext(brief)

        return PlainTextResponse(content, media_type="text/plain")
